version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "tomasnorre"
    assignees:
      - "tomasnorre"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "tomasnorre"
    assignees:
      - "tomasnorre"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "tomasnorre"
    assignees:
      - "tomasnorre"