apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: site-dk-tomasnorre-blog
  namespace: default
spec:
  secretName: site-dk-tomasnorre-blog
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "blog.tomasnorre.dk"