# Name of your application. Used to uniquely configure containers.
service: dk-tomasnorre-blog
# Name of the container image.
image: tomasnorre/blog

# Deploy to these servers.
servers:
  web:
    - 116.203.152.185

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
proxy:
  ssl: true
  host: blog.tomasnorre.dk

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: docker.tomasnorre.dk
  username: registry

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
