name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"

jobs:
  Build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up PHP Version 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2

      - name: Composer install
        run: composer install

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.tomasnorre.dk
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Container
        run: docker build -t docker.tomasnorre.dk/dk-tomasnorre-blog:$GITHUB_SHA .

      - name: Push Container to Registry
        run: |
          docker tag docker.tomasnorre.dk/dk-tomasnorre-blog:$GITHUB_SHA docker.tomasnorre.dk/dk-tomasnorre-blog:latest
          docker push docker.tomasnorre.dk/dk-tomasnorre-blog:$GITHUB_SHA
          docker push docker.tomasnorre.dk/dk-tomasnorre-blog:latest
          

  Deploy:
    runs-on: ubuntu-22.04
    needs: Build

    steps:
      - uses: actions/checkout@v1
      - uses: tomasnorre/gha-kubectl@v1
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f deploy/ingress.yml -f deploy/service.yaml -f deploy/deployment.yml -f deploy/certificate.yml

