name: CI

on:
  push:
    branches:
      - "kamal"

env:
  KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}

jobs:
  Build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan 95.216.189.171 >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          echo "SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None ssh-add -

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install Kamal
        run: gem install kamal

      - name: Build and deploy
        run: KAMAL_SECRET_KEY_BASE=$(openssl rand -hex 64) kamal deploy

  Test:
    runs-on: ubuntu-24.04
    needs: Build
    steps:
      - uses: 7th-green/gha-playwright@v1.0.3
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: BASE_URL=https://stage.blog.tomasnorre.dk npx playwright test