name: CI

on:
  push:
    branches:
      - "main"

jobs:
  Build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP Version 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2

      - name: Composer install
        run: composer install

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install && npm run prod

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.tomasnorre.dk
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Container
        run: docker build -t docker.tomasnorre.dk/dk-tomasnorre-blog:latest .

      - name: Push Container to Registry
        run: docker push docker.tomasnorre.dk/dk-tomasnorre-blog:latest

  Deploy:
    runs-on: ubuntu-22.04
    needs: Build

    steps:
      - uses: actions/checkout@v4
      - uses: tomasnorre/gha-kubectl@v1
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f deploy/ingress.yml -f deploy/service.yml -f deploy/deployment.yml -f deploy/certificate.yml
      - uses: tomasnorre/gha-kubectl@v1
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete pods -l app=site-dk-tomasnorre-blog -n default
