name: CI

on:
  push:
    branches:
      - "kamal"

jobs:
  Build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kamal
        run: gem install kamal

      - name: Build and deploy
        run: kamal deploy

  Test:
    runs-on: ubuntu-24.04
    needs: Deploy
    steps:
      - uses: 7th-green/gha-playwright@v1.0.3
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: BASE_URL=https://blog.tomasnorre.dk npx playwright test