name: CI

on:
  push:
    branches:
      - "main"

jobs:
  Build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP Version 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Composer install
        run: composer install

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm install && npm run prod

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: docker.tomasnorre.dk
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Container
        run: docker build -t docker.tomasnorre.dk/dk-tomasnorre-blog:latest .

      - name: Push Container to Registry
        run: docker push docker.tomasnorre.dk/dk-tomasnorre-blog:latest

  Deploy:
    runs-on: ubuntu-24.04
    needs: Build

    steps:
      - uses: actions/checkout@v4
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f deploy/ingress.yml -f deploy/service.yml -f deploy/deployment.yml -f deploy/certificate.yml
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete pods -l app=site-dk-tomasnorre-blog -n default

  Test:
    runs-on: ubuntu-24.04
    needs: Deploy
    steps:
      - uses: 7th-green/gha-playwright@v1.0.1
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: BASE_URL=https://blog.tomasnorre.dk npx playwright test