name: CI

on:
  push:
    branches:
      - "main"

env:
  KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_DOCKER_TOMASNORRE_DK_PASSWORD }}

jobs:
  Build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install Kamal
        run: gem install kamal

      - name: Build and deploy
        run: kamal deploy

  Test:
    runs-on: ubuntu-24.04
    needs: Build
    steps:
      - uses: 7th-green/gha-playwright@v1.0.3
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: BASE_URL=https://blog.tomasnorre.dk npx playwright test